### PR TITLE
1.20.x!

### PR DESCRIPTION
**Pull request by Stoutscientist**
Tested working on 1.20-1.20.4!

### CODE REVIEW

**Comment by zanyahtzee** [comment]
unfathomably based

**Comment by Stoutscientist** [comment]
I woke up 30 minutes ago lol

**Comment by SpaceXVI** [comment]
I am genuinely scared of how quick you are... I agree with zanayahtzee, unfathomably based.
Do you want me to publish the upload myself or will you do it yourself? Up to you here!

Either way, tysm bro :)

**Comment by Stoutscientist** [comment]
> I am genuinely scared of how quick you are... I agree with zanayahtzee, unfathomably based.
> Do you want me to publish the upload myself or will you do it yourself? Up to you here!
> 
> Either way, tysm bro :)

NP, and I don't mind either way, whichever is easier for you!

**Comment by SpaceXVI** [comment]
Well then I think it's best if I put the update myself up on curseforge so it's more noticeable for people who were anticipating an update, I'll say it again but thank you stout for your efforts :)

EDIT : Tiny request but do you have a discord by any chance? It'd make communication easier for me in the current time.

**Comment by Stoutscientist** [comment]
Yes! My name is the same as on here.

**Pull request merged**
