### PR TITLE
es_es (spanish)

### PR DESCRIPTION
**Pull request by swagmeister69420**
githu
b

### CODE REVIEW

**Comment by SpaceXVI** [comment]
SUS

**Comment by swagmeister69420** [comment]
im not even gonna bother to steep so far down from grace to make an among us joke

**Comment by swagmeister69420** [comment]
that convinced ya? GOOD.

**Comment by SpaceXVI** [comment]
noob.

**Comment by swagmeister69420** [comment]
"so like... i dont know the languages. so i dont check the translations. i dont think anybody does really." -ms55, also calls me noob

**Pull request merged**
