### PR TITLE
Fix crash on 1.19.4

### PR DESCRIPTION
**Pull request by Stoutscientist**
Using the mod on 1.19.4 results in a crash, so I tried fixing it to the best of my ability. During my testing, it fully works but you can double-check if you want, and the code probably needs to be cleaned up.

### CODE REVIEW

**Comment by SpaceXVI** [comment]
I didn't really have much time to see why it crashes so thank you for this! Looks good, will hopefully release the update today

**Comment by Stoutscientist** [comment]
Awesome, thanks!

**Comment by Stoutscientist** [comment]
Is it ok if I release the fix on CF/Modrinth as a fork?

**Comment by SpaceXVI** [comment]
I completely forgot about this, I got caught up with schoolwork and I am extremely sorry for delaying this but no worries, I'm free tomorrow and should be able to push out the update myself. Thanks for your effort.

**Comment by Stoutscientist** [comment]
> I completely forgot about this, I got caught up with schoolwork and I am extremely sorry for delaying this but no worries, I'm free tomorrow and should be able to push out the update myself. Thanks for your effort.

No problem lol, all good.

**Comment by SpaceXVI** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/rough-tweaks-revamped/files/4747421

There it is! Again, thank you for your help.

**Comment by Stoutscientist** [comment]
You're welcome! And thank you!

**Pull request merged**
